### ISSUE TITLE
Rejected promise from Either

### ISSUE THREAD

**Issue by seymen** [nwolverson/purescript-aff-promise#18]
Hi there

I was wondering if there is a reusable pattern that will result in a rejected promise given a `Left Error`.

E.g. assume I have a function that returns `Aff (Either Error a)` and I would like to convert that to a Promise to be sent off to a JS code. How can I convert that Aff into a rejected promise if my function returns Aff `Left Error`? Currently with `fromAff`, I am always getting a resolved promise even if I have an Error in Aff.

**Comment by nwolverson** [comment]
This is just a question about `Aff` - `Aff` already embeds errors, so `Aff (Either Error a)` can be lifted up to an `Aff a` by promoting the `Error` into the `Aff` itself.

`Aff` is a `MonadThrow` so you can use 

```
throwError :: forall a. Error -> Aff a
```

i.e. something like `... >>= either throwError pure`

**Comment by seymen** [comment]
Brilliant! Worked like a charm. Thanks a lot for taking the time.
