### ISSUE TITLE
Use Promise type from web-promise library

### ISSUE THREAD

**Issue by thomashoneyman** [nwolverson/purescript-aff-promise#24]
Do you have any interest in reusing the `Promise` type as exposed in the `web-promise` library? See:
https://github.com/purescript-web/purescript-web-promise

A bit of work has gone in to the `Promise` representation in that library, and it may be useful to reuse the type here. I'd like to use `aff-promise` in projects that are already using the type from that library, but unless I'm mistaken that's not currently possible.

**Comment by jamesdbrock** [comment]
Would you like a PR for this @nwolverson ?

**Comment by nwolverson** [comment]
Sorry I am away just now but yes I would take a pr for this yes

**Comment by i-am-the-slime** [comment]
Shouldn't the `web-promise` library be called `js-promise`

**Comment by nwolverson** [comment]
Resolved by #30
