### ISSUE TITLE
Move to contrib, or rowtype-yoga?

### ISSUE THREAD

**Issue by jamesdbrock** [nwolverson/purescript-aff-promise#31]
I think this library is a good candidate for community ownership. What do you think @nwolverson ?

**Comment by jamesdbrock** [comment]
contrib would make sense, since you're a contrib member.

**Comment by nwolverson** [comment]
I have no objection to moving to contrib.

I have no idea what a rowtype-yoga is.

**Comment by JordanMartinez** [comment]
I'm for moving it to `contrib` since this was one repo that slowed down the breaking changes we did in `0.15` because we didn't have access to it but other contrib libs depend on it.

**Comment by jamesdbrock** [comment]
@nwolverson If you transfer this package to contrib, then I'll do any maintenance work which needs to be done to publish new versions.

**Comment by nwolverson** [comment]
It's being moved shortly, there are breaking changes for release including re-namespacing, which will be for release in the new location. I have no desire indeed to hold onto doing releases as I'm clearly bad at getting around to it, thanks.

**Comment by jamesdbrock** [comment]
Cool, it sounds like you've got this under control. I'll leave you to it then. Let me know if you want me to do any of the boring work.

**Comment by nwolverson** [comment]
Tis done
