### ISSUE TITLE
Upload to pursuit

### ISSUE THREAD

**Issue by icyrockcom** [nwolverson/purescript-aff-promise#6]
As per discussion with hdgarrood here:

* https://github.com/purescript/pursuit/issues/298

I've published this to pursuit, since it got removed, probably during the purescript upgrade.

https://pursuit.purescript.org/packages/purescript-aff-promise/0.5.0

Just letting you know via this issue. Let me know if you consider this upload fine from your end. Just trying to gauge if:

* People are OK in general with me uploading their repositories to pursuit
* I should be creating issues such as this one when I upload, to let them know, or if just uploading is fine

I'll close this issue in a bit.

**Comment by nwolverson** [comment]
Thanks. I have no problem with this, I publish on tag automatically but wouldn't think (or bother) to re-upload. Don't think an issue is required (but seems nice thought).

**Comment by icyrockcom** [comment]
Great, thanks @nwolverson!
