### ISSUE TITLE
Add examples in documentation

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/purescript-aff-promise#8]
There are some examples in the tests but some (perhaps more compelling) examples could be given in high-level docs which help explain what the library is *for*.

**Comment by justinwoo** [comment]
Maybe the [milkis](https://github.com/justinwoo/purescript-milkis/blob/f337c198597a6d27733497cca510543df5365db3/src/Milkis.purs#L43) code can provide an easy example

**Comment by nwolverson** [comment]
@justinwoo thanks, I'll use that, but I think your code is actually a bit dodgy, a warning example - your `fetch` actually performs a network request even if you don't run the `Aff` because you define a bad FFI function - I'll raise an issue.

**Comment by justinwoo** [comment]
yeah, our laziness at the meetup got the better of us :D
